### ISSUE TITLE
Save user provided url if dataset is created from a url rather than an upload.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-service#105]
The url will be a new optional field in the dataset's `meta.json` file.

### Tasks

* [x] Update the internal database schema
* [x] Tag the new schema version
* [x] Wait for the new database container to build in Jenkins
* [x] Update the VDI service docker-compose.yml file to use the new database tag
* [x] Add the new field to VDI meta interface and class
* [x] Publish the new version of the commons library
* [x] Update the plugin service to use the new version of the commons library
* [x] PR the change to the plugin service
* [x] Tag the updated plugin service
* [x] Wait for jenkins to build the new plugin service tag
* [x] Update the plugin base image to use the new plugin service tag
* [x] Tag the plugin base image
* [x] Wait for jenkins to build the new plugin base image
* [x] Update the bigwig plugin to use the new plugin base image
* [x] Update the genelist plugin to use the new plugin base image
* [x] Update the rnaseq plugin to use the new plugin base image
* [x] Update the isa plugin to use the new plugin base image
* [x] Update the biom plugin to use the new plugin base image
* [x] Update the VDI service to use the new commons version
* [x] Update the VDI service raml/jaxrs to include the new field
* [x] Update the VDI service queries to use the new database field(s) and write to the new model property or properties
* [x] Update the VDI service to pass the data through from the database to the API types
* [x] Test upload via url
