### ISSUE TITLE
Add a new mandatory `origin` field to the dataset meta for tracking dataset origin.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-service#106]
The field will be a text field that may be set with a source such as `website`, `nephele`, or `galaxy`.  The field should not be an enum as the sources may change.

This field will be provided by the client, likely by a hidden field.

### Tasks

* [x] Update the vdi commons library to add the new field.
* [x] Update the plugin server to use the new vdi commons library
* [x] tag the plugin server with a new version
* [x] Wait for jenkins to build the new image
* [x] Update the plugin base image to use the new plugin server
* [x] tag the plugin base image with a new version
* [x] Wait for jenkins to build the new base image version
* [x] Update the GeneList plugin to use the new base image
* [x] Update the RNASeq plugin to use the new base image
* [x] Update the BIOM plugin to use the new base image
* [x] Update the ISA plugin to use the new base image
* [x] Update the BigWig plugin to use the new base image
* [x] Update the VDI service to use the new commons library
* [x] Add the new meta field to the database schema
* [x] Tag the new database schema
* [x] Wait for the new database schema to be built in jenkins
* [x] Update the docker compose in VDI service to use the new database schema version.
* [x] Update the VDI service API to add the new field
