### ISSUE TITLE
Store dataset creation date in `meta.json`

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-service#179]
For normal uploads this value will be set to the dataset upload time.  For admin user-proxy uploads this value may be provided.  This is to maintain user dataset creation dates from the legacy system.

This change will require an update to the cache-db schema to store the new meta value.

**Comment by Foxcapades** [comment]
**UPDATE**

Due to crossed wires a bad attempt was made to implement this.  That attempt involved accepting a creation date override value on the user-proxy dataset upload admin endpoint and writing it to the `vdi.datasets.created` field in postgres.  That is a misuse of the field and does not implement the base requirements.  Additionally, the date in the postgres table is not synchronized cross campus as it does not appear in MinIO.

**Comment by Foxcapades** [comment]
**UPDATE**

We will be keeping the bad implementation that repurposed the `vdi.datasets.created` column to track datasets' original creation date.  Now to track the insert date of the dataset record into postgres, we will add a new column to the `vdi.datasets` table: `vdi.datasets.inserted`.

**Comment by Foxcapades** [comment]
**Preparation**

* [x] Update the schema in the vdi-internal-db repo
* [ ] Update vdi-component-common to add the new field to the dataset meta pojo
* [ ] Add a temporary, one-off migration script to VDI to update the existing postgres instances to avoid needing the database volumes to be dropped.
* [ ] Wire the new `inserted` column into the VDI service
* [ ] Update the plugin handler server to use the new vdi-component-common version and tag a new release
* [ ] On a branch, update the plugin base image to use the new plugin handler server version
* [ ] On a branch, update the bigwig plugin to use the branched base image
* [ ] On a branch, update the biom plugin to use the branched base image
* [ ] On a branch, update the example plugin to use the branched base image
* [ ] On a branch, update the genelist plugin to use the branched base image
* [ ] On a branch, update the isasimple plugin to use the branched base image
* [ ] On a branch, update the rnaseq plugin to use the branched base image

**Deployment**

* [ ] Bulk delete all datasets in dev VDI via the API
* [ ] merge the plugin base image branch to main and tag new version
* [ ] update bigwig plugin branch to use new base image tag, merge to main
* [ ] update biom plugin branch to use new base image tag, merge to main
* [ ] update example plugin branch to use new base image tag, merge to main
* [ ] update genelist plugin branch to use new base image tag, merge to main
* [ ] update isasimple plugin branch to use new base image tag, merge to main
* [ ] update rnaseq plugin branch to use new base image tag, merge to main
* [ ] merge vdi service update branch to main

**Cleanup**

Once VDI has been redeployed on both campuses and the migration script has succeeded...

* [ ] Remove migration script from VDI service
