### ISSUE TITLE
Ensure VDI processes handle unexpected shutdowns in a non-breaking manner.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-service#271]
* [x] Event Router: Rabbit events in local queue will be lost, reconciler should hopefully catch.
* [x] Pruner: **Problem if interrupted during db purge** - #274
* [x] Reconciler: **Problem if interrupted during hard delete** - #274
* [x] Rest Service: **Problem if interrupted with queued uploads** - #198
* [x] Hard Delete Lane: Presently just logs hard deletes
* [x] Import Lane: **Problem if interrupted mid-import** - #227
* [x] Install Lane: **Problem if interrupted mid-install** #217 #218
* [x] Reconciliation Lane: If interrupted, reconciler will catch on startup.
* [x] Sharing Lane: If interrupted, reconciler will catch on startup
* [x] Soft Delete Lane: If interrupted, reconciler will catch on startup.
* [x] Update Meta Lane: If interrupted, reconciler will catch on startup (update meta lane doesn't care if an update is already in progress: #275)
